### ISSUE TITLE
Cover / Curtain module support  added?

### ISSUE THREAD

**Issue by yiannosi** [eyesoft/home_assistant_buspro#8]
I understand that Cover/Curtain module is now supported. Fork merged !

Is it possible to reverse the direction of motor motion (open / close) without changing wiring?

ie interchange OPEN & CLOSE commands?

**Comment by IlPicasso** [comment]
> I understand that Cover/Curtain module is now supported. Fork merged !
> 
> Is it possible to reverse the direction of motor motion (open / close) without changing wiring?
> 
> ie interchange OPEN & CLOSE commands?

Yo could create a template entity and create scripts and reverse the commands
```
    covers:
      cortinasala4:
        device_class: curtain
        friendly_name: "Cortina Sala 4"
        value_template: "{{ 1 > 0 }}"
        open_cover:
          service: script.abrir_cortina_sala_1
        close_cover:
          service: script.cerrar_cortina_sala_1
        stop_cover:
          service: script.parar_cortina_sala_1
```



![image](https://github.com/user-attachments/assets/10b1fef6-a089-4532-98d8-121e018611a1)

**Comment by yiannosi** [comment]
> service: script.abrir_cortina_sala_1

Thanks for your reply!

I am afraid I am not that competent with HA yaml! 
How do you create scripts ie what's `script.abrir_cortina_sala_1` ?

I was thinking something like this would be nice if it was supported:

```
cover:
  - platform: buspro
    devices:
      1.12.1:
        name: Blind LivingRoom
        reverse: true
```

**Comment by IlPicasso** [comment]
> > service: script.abrir_cortina_sala_1
> 
> Thanks for your reply!
> 
> I am afraid I am not that competent with HA yaml! How do you create scripts ie what's `script.abrir_cortina_sala_1` ?
> 
> I was thinking something like this would be nice if it was supported:
> 
> ```
> cover:
>   - platform: buspro
>     devices:
>       1.12.1:
>         name: Blind LivingRoom
>         reverse: true
> ```

Thats not supported in the code

If you want to create the script go to automáticos, scripts

In the scripts section add new script AND make script call service open cover AND Select  the device

**Comment by yiannosi** [comment]
I did try to follow your advice above!
`covers:

    Back_Left_Blind:
      device_class: curtain
      friendly_name: "Back Left Blind"
      value_template: "{{ 1 > 0 }}"
      open_cover:
        service: script.open_back_left_blind
      close_cover:
        service: script.close_back_left_blind
      stop_cover:
        service: script.stop_back_left_blind          
       `

But it complains that "covers" platform not found.

Did you mean "cover' ?

**Comment by IlPicasso** [comment]
try following this scheme

https://hastebin.com/share/fugesodema.yaml

**Comment by yiannosi** [comment]
> try following this scheme

Thanks! That helped me sort it out.
Managed to set it up but the UP direction for some reason is always disabled even when the blind is fully down:

![image](https://github.com/user-attachments/assets/d711ad64-ae0b-4dd6-abf1-7de251fb8719)

**Comment by ashwarsadh** [comment]
I have improved upon Curtain Implementation by IlPicasso
Curtain Support with Position Control and Google Home supported 
Fork URL: 
https://github.com/ashwarsadh/home_assistant_buspro

**Comment by yiannosi** [comment]
> I have improved upon Curtain Implementation by IlPicasso Curtain Support with Position Control and Google Home supported Fork URL: https://github.com/ashwarsadh/home_assistant_buspro

Thats nice.
Does it also  support reversing of open-close direction?

**Comment by yiannosi** [comment]
Hi do you install this change ?
I have replaced the *.py files that have changed but I messed up the integration! :(

**Comment by IlPicasso** [comment]
> Hi do you install this change ? I have replaced the *.py files that have changed but I messed up the integration! :(

Delete HDL in HACS (Ignore any notice it gives you) 

Add this repo in HACS and install it, restart.
https://github.com/ashwarsadh/home_assistant_buspro

**Comment by yiannosi** [comment]
> Delete HDL in HACS (Ignore any notice it gives you)

Excellent! Got it working thanks!

I just wish there was a way to swap open-close commands for blinds in software. Otherwise I d have to change wiring.
Any chance of getting this done?

**Comment by vadimvros** [comment]
Hi everyone. Who knows, repository version 1.6.0 solved the issue of curtain control?

**Comment by Glazzanz** [comment]
> I have improved upon Curtain Implementation by IlPicasso Curtain Support with Position Control and Google Home supported Fork URL: https://github.com/ashwarsadh/home_assistant_buspro

Thanks for this @ashwarsadh @IlPicasso, I have added it as the following.  However its not using the opening_time when calculating the position of the curtain etc.

```
cover:
  - platform: buspro
    devices:
      1.61.1:
        name: Curtain - LivingRoom - Door
        opening_time: 8
      1.61.2:
        name: Curtain - LivingRoom - Dining
        opening_time: 5
      1.62.1:
        name: Curtain - LivingRoom - Back
        opening_time: 6
      1.62.2:
        name: Curtain - LivingRoom - Side
        opening_time: 6
```
